name: Build OpenVPN MSI (32+64位)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      
      - name: 构建 OpenVPN x64
        run: |
          choco install wget -y
          git clone https://github.com/OpenVPN/openvpn-build.git
          cd openvpn-build/windows-msi
          .\build.win.ps1 -arch x64
          .\package.win.ps1 -arch x64
          mkdir -p output
          copy output\*.msi ..\..\output-x64.msi

      - name: 构建 OpenVPN x86
        run: |
          cd openvpn-build/windows-msi
          .\build.win.ps1 -arch x86
          .\package.win.ps1 -arch x86
          copy output\*.msi ..\..\output-x86.msi

      - uses: actions/upload-artifact@v4
        with:
          name: openvpn-msi
          path: |
            output-x64.msi
            output-x86.msi
